---
title: "STAT325: named entity recognition analysis of XX"
author: "XX YOUR NAME HERE XX"
date: "2024-02-22"
date-format: iso
format: pdf
editor: source
---
  
```{r}
#| label: setup
#| include: false
library(mosaic)
library(tidyverse)
library(tidytext)
library(nametagger)
library(tictoc)
```

```{r}
file_name <- "anno_moby.Rds"
stopifnot(file.exists(file_name))
anno <- readRDS(file_name)
```

```{r}
token_with_chapters <- anno$token |>
  mutate(chapter_number = 
           cumsum(str_detect(token, regex("^CHAPTER", ignore_case = FALSE)) & tid == 1))

entity_with_chapters <- left_join(anno$entity, 
                                  token_with_chapters, 
                                  by = c("doc_id", "sid", "tid")) |>
  select(entity_type, entity, chapter_number)
```


```{r}
token_type_summary <- token_with_chapters |>
  group_by(chapter_number) |>
  summarize(total = n(),
            noun_count = sum(ifelse(upos == "NOUN", 1, 0)),
            noun_prop = noun_count/total,
            adj_count = sum(ifelse(upos == "ADJ", 1, 0)),
            adj_prop = adj_count/total,
            verb_count = sum(ifelse(upos == "VERB", 1, 0)),
            verb_prop = verb_count/total,
            proper_noun_count = sum(ifelse(upos == "PROPN", 1, 0)),
            proper_noun_prop = proper_noun_count/total,
            conj_count = sum(ifelse(upos == "CCONJ" | upos == "SCONJ", 1, 0)),
            conj_prop = conj_count/total,
            .groups = "drop")

entity_type_summary_no_total <- entity_with_chapters |>
  group_by(chapter_number) |>
  summarize(person_count = sum(ifelse(entity_type == "PERSON", 1, 0)),
            location_count = sum(ifelse(entity_type == "LOC", 1, 0)),
            time_count = sum(ifelse(entity_type == "TIME", 1, 0)),
            date_count = sum(ifelse(entity_type == "DATE", 1, 0)),
            .groups = "drop")
entity_type_summary <- inner_join(entity_type_summary_no_total, token_type_summary, by = "chapter_number") |>
  select(chapter_number, total, person_count, location_count, time_count, date_count) |>
  mutate(person_prop = person_count/total,
         location_prop = location_count/total,
         time_prop = time_count/total,
         date_prop = date_count/total)

write_csv(token_type_summary, "../token_type_summary.csv")



token_type_summary |>
      select(chapter_number,
             total,
             noun_count,
             noun_prop
             ) |>
      arrange(desc(noun_prop))

paste0("noun", "_count")

fig <- plot_ly(data = token_type_summary, x = ~chapter_number, y = ~noun_prop, type = "scatter")

# ggplot(token_type_summary, aes(x = chapter_number, y = verb_prop)) +
#   geom_point() +
#   geom_smooth(se = FALSE)
```
