---
title: "STAT325: MobyDick Shiny App Pre-Processing"
author: "XX Adam Rogers XX"
date: "2024-03-15"
date-format: iso
format: pdf
editor: source
---
  
```{r}
#| label: setup
#| include: false
library(mosaic)
library(tidyverse)
library(tidytext)
library(MobyDick)
```

```{r}
file_name <- "anno_moby.Rds"
stopifnot(file.exists(file_name))
anno <- readRDS(file_name)
```

```{r}
token_with_chapters <- anno$token |>
  # Add chapter number to tokenized text
  # Use tid == 1 to avoid edge case where text "CHAPTER" is within a chapter
  mutate(chapter_number = 
           cumsum(str_detect(token, 
                             regex("^CHAPTER", ignore_case = FALSE)) & tid == 1))

entity_with_chapters <- left_join(anno$entity, 
                                  token_with_chapters, 
                                  by = c("doc_id", "sid", "tid")) |>
  select(entity_type, entity, chapter_number)
```


```{r}
token_type_summary <- token_with_chapters |>
  group_by(chapter_number) |>
  summarize(total = n(),
            NOUN_count = sum(ifelse(upos == "NOUN", 1, 0)),
            NOUN_prop = round(NOUN_count/total, 4),
            ADJ_count = sum(ifelse(upos == "ADJ", 1, 0)),
            ADJ_prop = round(ADJ_count/total, 4),
            VERB_count = sum(ifelse(upos == "VERB", 1, 0)),
            VERB_prop = round(VERB_count/total, 4),
            ADV_count = sum(ifelse(upos == "ADV", 1, 0)),
            ADV_prop = round(ADV_count/total, 4),
            PROPN_count = sum(ifelse(upos == "PROPN", 1, 0)),
            PROPN_prop = round(PROPN_count/total, 4),
            CONJ_count = sum(ifelse(upos == "CCONJ" | upos == "SCONJ", 1, 0)),
            CONJ_prop = round(CONJ_count/total, 4),
            PRON_count = sum(ifelse(upos == "PRON", 1, 0)),
            PRON_prop = round(PRON_count/total, 4),
            PUNCT_count = sum(ifelse(upos == "PUNCT", 1, 0)),
            PUNCT_prop = round(PUNCT_count/total, 4),
            .groups = "drop")

entity_type_summary_no_total <- entity_with_chapters |>
  group_by(chapter_number) |>
  summarize(person_count = sum(ifelse(entity_type == "PERSON", 1, 0)),
            location_count = sum(ifelse(entity_type == "LOC", 1, 0)),
            time_count = sum(ifelse(entity_type == "TIME", 1, 0)),
            date_count = sum(ifelse(entity_type == "DATE", 1, 0)),
            .groups = "drop")

entity_type_summary <- inner_join(entity_type_summary_no_total, token_type_summary, by = "chapter_number") |>
  select(chapter_number, total, person_count, location_count, time_count, date_count) |>
  mutate(person_prop = person_count/total,
         location_prop = location_count/total,
         time_prop = time_count/total,
         date_prop = date_count/total)

write_csv(token_with_chapters, "token_with_chapters.csv")
write_csv(token_type_summary, "token_type_summary.csv")
```


```{r}
unique(token_with_chapters$upos)


# Limitation: data isn't in R folder
# Paragraphs aren't cleaned up (no new lines)

```
